import React from "react";
import Head from "next/head";

import OGImage from "@/assets/images/og_image.png";

const WebsiteHead = () => {
  return (
    <Head>
      <title>US Imports</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.png" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
        href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
        rel="stylesheet"
      />
      <meta property="og:type" content="website" />
      <meta property="og:title" content="US Imports" />
      <meta
        property="og:description"
        content="Importe suas mercadorias com facilidade e rapidez"
      />
      <meta property="og:image" itemProp="image" content={OGImage.src} />
    </Head>
  );
};

export default WebsiteHead;
